language: php

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
  - composer install
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - npm prune
  - phpenv versions
  - npm --version
  - node --version

script:
  - grunt phpcs
  - grunt default
